apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app04-root-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: git@github.com:tbthesam3/argocd-lab-with-helm.git
    targetRevision: HEAD
    path: apps
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
