apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app04-dev
  namespace: argocd
spec:
  project: default
  source:
    repoURL: git@github.com:tbthesam3/argocd-lab-with-helm.git
    path: charts/app04-helm
    targetRevision: HEAD
    helm:
      valueFiles:
        - ../../environments/dev/app04-values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
